name: gbk_clearlag
main: me.gabrielbk.gbk_clearlag
author: GabrielBk
version: 1.0.0
api-version: 1.13
commands:
  gclear:
    description: Limpa entidades, mobs e itens
    usage: /gclear <tudo|mobs|itens|reload>
    permission: gbkclearlag.use
permissions:
  gbkclearlag.use:
    default: op
